version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: flask_app
    ports:
      - "8001:8001"
    command: gunicorn -w 1 -b 0.0.0.0:8001 wsgi:app

  nginx:
    container_name: nginx
    restart: always
    build: nginx
    ports:
      - "81:81"
      - "443:443"
    depends_on:
      - flask_app
    volumes:
      - /etc/letsencrypt/live/www.topicalisland.net/fullchain.pem:/etc/nginx/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/www.topicalisland.net/privkey.pem:/etc/nginx/ssl/certs/privkey.pem
