# This is a basic workflow to help you get started with Actions
name: CICD
  
# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: rsycn code to server 
        uses: Burnett01/rsync-deployments@5.2
        with:
          switches: -avzr
          path: ./src
          remote_path: /home/devuser/topical-island
          remote_host: ${{ secrets.SERVER_IP_ADDRESS }}
          remote_user: devuser
          remote_key: ${{ secrets.DEVUSER_SSH_PRIVATE_KEY }}
                
      - name: rebuild docker containers over ssh
        uses: fifsky/ssh-action@v0.0.6
        with:
          # Command to execute on the remote server.
          command: |
            cd topical-island/src
            ls -a
            bash build.sh
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          user: devuser
          key: ${{ secrets.DEVUSER_SSH_PRIVATE_KEY }}
